[project]
name = "kernemul"
languages = ["CXX"]

[conditions]
windows = "WIN32"

[fetch-content.spdlog]
git = "https://github.com/gabime/spdlog"
tag = "v1.x"

[fetch-content.unicorn]
git = "https://github.com/unicorn-engine/unicorn"
tag = "master"

[fetch-content.raw_pdb]
git = "https://github.com/MolecularMatters/raw_pdb"
tag = "main"

[fetch-content.Boost]
url = "https://github.com/boostorg/boost/releases/download/boost-1.86.0/boost-1.86.0-cmake.tar.xz"

[find-package.OpenSSL]
required = true

[target.kernemul]
type = "executable"
sources = ["src/**.cpp", "src/**.hpp"]
include-directories = ["src", "vendor/pe/src", "vendor/ia32-doc/out"]
compile-features = ["cxx_std_23"]
link-libraries = ["spdlog::spdlog", "unicorn", "raw_pdb", "Boost::beast", "OpenSSL::SSL", "OpenSSL::Crypto"]
windows.link-libraries = ["ws2_32"]
compile-options = ["-Wno-changes-meaning"]
