// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_EVENT_FBS_H_
#define FLATBUFFERS_GENERATED_EVENT_FBS_H_

#include "flatbuffers/flatbuffers.h"

// version check relaxed for cross-platform builds
static_assert(FLATBUFFERS_VERSION_MAJOR >= 23,
             "FlatBuffers version too old");

namespace fbs {

struct Buffer;
struct BufferBuilder;
struct BufferT;

struct ArgumentRef;
struct ArgumentRefBuilder;
struct ArgumentRefT;

struct PatchRef;
struct PatchRefBuilder;
struct PatchRefT;

struct ImmediateTrigger;
struct ImmediateTriggerBuilder;
struct ImmediateTriggerT;

struct AfterDriverEntryTrigger;
struct AfterDriverEntryTriggerBuilder;
struct AfterDriverEntryTriggerT;

struct CallTarget;
struct CallTargetBuilder;
struct CallTargetT;

struct IoctlTarget;
struct IoctlTargetBuilder;
struct IoctlTargetT;

struct Event;
struct EventBuilder;
struct EventT;

struct EventResult;
struct EventResultBuilder;
struct EventResultT;

struct ModifiedBuffer;
struct ModifiedBufferBuilder;
struct ModifiedBufferT;

struct ResultSequence;
struct ResultSequenceBuilder;
struct ResultSequenceT;

enum class BufferRef : uint8_t {
  NONE = 0,
  ArgumentRef = 1,
  PatchRef = 2,
  MIN = NONE,
  MAX = PatchRef
};

inline const BufferRef (&EnumValuesBufferRef())[3] {
  static const BufferRef values[] = {
    BufferRef::NONE,
    BufferRef::ArgumentRef,
    BufferRef::PatchRef
  };
  return values;
}

inline const char * const *EnumNamesBufferRef() {
  static const char * const names[4] = {
    "NONE",
    "ArgumentRef",
    "PatchRef",
    nullptr
  };
  return names;
}

inline const char *EnumNameBufferRef(BufferRef e) {
  if (::flatbuffers::IsOutRange(e, BufferRef::NONE, BufferRef::PatchRef)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesBufferRef()[index];
}

template<typename T> struct BufferRefTraits {
  static const BufferRef enum_value = BufferRef::NONE;
};

template<> struct BufferRefTraits<fbs::ArgumentRef> {
  static const BufferRef enum_value = BufferRef::ArgumentRef;
};

template<> struct BufferRefTraits<fbs::PatchRef> {
  static const BufferRef enum_value = BufferRef::PatchRef;
};

template<typename T> struct BufferRefUnionTraits {
  static const BufferRef enum_value = BufferRef::NONE;
};

template<> struct BufferRefUnionTraits<fbs::ArgumentRefT> {
  static const BufferRef enum_value = BufferRef::ArgumentRef;
};

template<> struct BufferRefUnionTraits<fbs::PatchRefT> {
  static const BufferRef enum_value = BufferRef::PatchRef;
};

struct BufferRefUnion {
  BufferRef type;
  void *value;

  BufferRefUnion() : type(BufferRef::NONE), value(nullptr) {}
  BufferRefUnion(BufferRefUnion&& u) FLATBUFFERS_NOEXCEPT :
    type(BufferRef::NONE), value(nullptr)
    { std::swap(type, u.type); std::swap(value, u.value); }
  BufferRefUnion(const BufferRefUnion &);
  BufferRefUnion &operator=(const BufferRefUnion &u)
    { BufferRefUnion t(u); std::swap(type, t.type); std::swap(value, t.value); return *this; }
  BufferRefUnion &operator=(BufferRefUnion &&u) FLATBUFFERS_NOEXCEPT
    { std::swap(type, u.type); std::swap(value, u.value); return *this; }
  ~BufferRefUnion() { Reset(); }

  void Reset();

  template <typename T>
  void Set(T&& val) {
    typedef typename std::remove_reference<T>::type RT;
    Reset();
    type = BufferRefUnionTraits<RT>::enum_value;
    if (type != BufferRef::NONE) {
      value = new RT(std::forward<T>(val));
    }
  }

  static void *UnPack(const void *obj, BufferRef type, const ::flatbuffers::resolver_function_t *resolver);
  ::flatbuffers::Offset<void> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr) const;

  fbs::ArgumentRefT *AsArgumentRef() {
    return type == BufferRef::ArgumentRef ?
      reinterpret_cast<fbs::ArgumentRefT *>(value) : nullptr;
  }
  const fbs::ArgumentRefT *AsArgumentRef() const {
    return type == BufferRef::ArgumentRef ?
      reinterpret_cast<const fbs::ArgumentRefT *>(value) : nullptr;
  }
  fbs::PatchRefT *AsPatchRef() {
    return type == BufferRef::PatchRef ?
      reinterpret_cast<fbs::PatchRefT *>(value) : nullptr;
  }
  const fbs::PatchRefT *AsPatchRef() const {
    return type == BufferRef::PatchRef ?
      reinterpret_cast<const fbs::PatchRefT *>(value) : nullptr;
  }
};

bool VerifyBufferRef(::flatbuffers::Verifier &verifier, const void *obj, BufferRef type);
bool VerifyBufferRefVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<BufferRef> *types);

enum class Trigger : uint8_t {
  NONE = 0,
  ImmediateTrigger = 1,
  AfterDriverEntryTrigger = 2,
  MIN = NONE,
  MAX = AfterDriverEntryTrigger
};

inline const Trigger (&EnumValuesTrigger())[3] {
  static const Trigger values[] = {
    Trigger::NONE,
    Trigger::ImmediateTrigger,
    Trigger::AfterDriverEntryTrigger
  };
  return values;
}

inline const char * const *EnumNamesTrigger() {
  static const char * const names[4] = {
    "NONE",
    "ImmediateTrigger",
    "AfterDriverEntryTrigger",
    nullptr
  };
  return names;
}

inline const char *EnumNameTrigger(Trigger e) {
  if (::flatbuffers::IsOutRange(e, Trigger::NONE, Trigger::AfterDriverEntryTrigger)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesTrigger()[index];
}

template<typename T> struct TriggerTraits {
  static const Trigger enum_value = Trigger::NONE;
};

template<> struct TriggerTraits<fbs::ImmediateTrigger> {
  static const Trigger enum_value = Trigger::ImmediateTrigger;
};

template<> struct TriggerTraits<fbs::AfterDriverEntryTrigger> {
  static const Trigger enum_value = Trigger::AfterDriverEntryTrigger;
};

template<typename T> struct TriggerUnionTraits {
  static const Trigger enum_value = Trigger::NONE;
};

template<> struct TriggerUnionTraits<fbs::ImmediateTriggerT> {
  static const Trigger enum_value = Trigger::ImmediateTrigger;
};

template<> struct TriggerUnionTraits<fbs::AfterDriverEntryTriggerT> {
  static const Trigger enum_value = Trigger::AfterDriverEntryTrigger;
};

struct TriggerUnion {
  Trigger type;
  void *value;

  TriggerUnion() : type(Trigger::NONE), value(nullptr) {}
  TriggerUnion(TriggerUnion&& u) FLATBUFFERS_NOEXCEPT :
    type(Trigger::NONE), value(nullptr)
    { std::swap(type, u.type); std::swap(value, u.value); }
  TriggerUnion(const TriggerUnion &);
  TriggerUnion &operator=(const TriggerUnion &u)
    { TriggerUnion t(u); std::swap(type, t.type); std::swap(value, t.value); return *this; }
  TriggerUnion &operator=(TriggerUnion &&u) FLATBUFFERS_NOEXCEPT
    { std::swap(type, u.type); std::swap(value, u.value); return *this; }
  ~TriggerUnion() { Reset(); }

  void Reset();

  template <typename T>
  void Set(T&& val) {
    typedef typename std::remove_reference<T>::type RT;
    Reset();
    type = TriggerUnionTraits<RT>::enum_value;
    if (type != Trigger::NONE) {
      value = new RT(std::forward<T>(val));
    }
  }

  static void *UnPack(const void *obj, Trigger type, const ::flatbuffers::resolver_function_t *resolver);
  ::flatbuffers::Offset<void> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr) const;

  fbs::ImmediateTriggerT *AsImmediateTrigger() {
    return type == Trigger::ImmediateTrigger ?
      reinterpret_cast<fbs::ImmediateTriggerT *>(value) : nullptr;
  }
  const fbs::ImmediateTriggerT *AsImmediateTrigger() const {
    return type == Trigger::ImmediateTrigger ?
      reinterpret_cast<const fbs::ImmediateTriggerT *>(value) : nullptr;
  }
  fbs::AfterDriverEntryTriggerT *AsAfterDriverEntryTrigger() {
    return type == Trigger::AfterDriverEntryTrigger ?
      reinterpret_cast<fbs::AfterDriverEntryTriggerT *>(value) : nullptr;
  }
  const fbs::AfterDriverEntryTriggerT *AsAfterDriverEntryTrigger() const {
    return type == Trigger::AfterDriverEntryTrigger ?
      reinterpret_cast<const fbs::AfterDriverEntryTriggerT *>(value) : nullptr;
  }
};

bool VerifyTrigger(::flatbuffers::Verifier &verifier, const void *obj, Trigger type);
bool VerifyTriggerVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<Trigger> *types);

enum class Target : uint8_t {
  NONE = 0,
  CallTarget = 1,
  IoctlTarget = 2,
  MIN = NONE,
  MAX = IoctlTarget
};

inline const Target (&EnumValuesTarget())[3] {
  static const Target values[] = {
    Target::NONE,
    Target::CallTarget,
    Target::IoctlTarget
  };
  return values;
}

inline const char * const *EnumNamesTarget() {
  static const char * const names[4] = {
    "NONE",
    "CallTarget",
    "IoctlTarget",
    nullptr
  };
  return names;
}

inline const char *EnumNameTarget(Target e) {
  if (::flatbuffers::IsOutRange(e, Target::NONE, Target::IoctlTarget)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesTarget()[index];
}

template<typename T> struct TargetTraits {
  static const Target enum_value = Target::NONE;
};

template<> struct TargetTraits<fbs::CallTarget> {
  static const Target enum_value = Target::CallTarget;
};

template<> struct TargetTraits<fbs::IoctlTarget> {
  static const Target enum_value = Target::IoctlTarget;
};

template<typename T> struct TargetUnionTraits {
  static const Target enum_value = Target::NONE;
};

template<> struct TargetUnionTraits<fbs::CallTargetT> {
  static const Target enum_value = Target::CallTarget;
};

template<> struct TargetUnionTraits<fbs::IoctlTargetT> {
  static const Target enum_value = Target::IoctlTarget;
};

struct TargetUnion {
  Target type;
  void *value;

  TargetUnion() : type(Target::NONE), value(nullptr) {}
  TargetUnion(TargetUnion&& u) FLATBUFFERS_NOEXCEPT :
    type(Target::NONE), value(nullptr)
    { std::swap(type, u.type); std::swap(value, u.value); }
  TargetUnion(const TargetUnion &);
  TargetUnion &operator=(const TargetUnion &u)
    { TargetUnion t(u); std::swap(type, t.type); std::swap(value, t.value); return *this; }
  TargetUnion &operator=(TargetUnion &&u) FLATBUFFERS_NOEXCEPT
    { std::swap(type, u.type); std::swap(value, u.value); return *this; }
  ~TargetUnion() { Reset(); }

  void Reset();

  template <typename T>
  void Set(T&& val) {
    typedef typename std::remove_reference<T>::type RT;
    Reset();
    type = TargetUnionTraits<RT>::enum_value;
    if (type != Target::NONE) {
      value = new RT(std::forward<T>(val));
    }
  }

  static void *UnPack(const void *obj, Target type, const ::flatbuffers::resolver_function_t *resolver);
  ::flatbuffers::Offset<void> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr) const;

  fbs::CallTargetT *AsCallTarget() {
    return type == Target::CallTarget ?
      reinterpret_cast<fbs::CallTargetT *>(value) : nullptr;
  }
  const fbs::CallTargetT *AsCallTarget() const {
    return type == Target::CallTarget ?
      reinterpret_cast<const fbs::CallTargetT *>(value) : nullptr;
  }
  fbs::IoctlTargetT *AsIoctlTarget() {
    return type == Target::IoctlTarget ?
      reinterpret_cast<fbs::IoctlTargetT *>(value) : nullptr;
  }
  const fbs::IoctlTargetT *AsIoctlTarget() const {
    return type == Target::IoctlTarget ?
      reinterpret_cast<const fbs::IoctlTargetT *>(value) : nullptr;
  }
};

bool VerifyTarget(::flatbuffers::Verifier &verifier, const void *obj, Target type);
bool VerifyTargetVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<Target> *types);

struct BufferT : public ::flatbuffers::NativeTable {
  typedef Buffer TableType;
  std::vector<uint8_t> data{};
  uint32_t size = 0;
};

struct Buffer FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BufferT NativeTableType;
  typedef BufferBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DATA = 4,
    VT_SIZE = 6
  };
  const ::flatbuffers::Vector<uint8_t> *data() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_DATA);
  }
  uint32_t size() const {
    return GetField<uint32_t>(VT_SIZE, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           VerifyField<uint32_t>(verifier, VT_SIZE, 4) &&
           verifier.EndTable();
  }
  BufferT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(BufferT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Buffer> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BufferT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct BufferBuilder {
  typedef Buffer Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_data(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data) {
    fbb_.AddOffset(Buffer::VT_DATA, data);
  }
  void add_size(uint32_t size) {
    fbb_.AddElement<uint32_t>(Buffer::VT_SIZE, size, 0);
  }
  explicit BufferBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Buffer> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Buffer>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Buffer> CreateBuffer(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data = 0,
    uint32_t size = 0) {
  BufferBuilder builder_(_fbb);
  builder_.add_size(size);
  builder_.add_data(data);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Buffer> CreateBufferDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *data = nullptr,
    uint32_t size = 0) {
  auto data__ = data ? _fbb.CreateVector<uint8_t>(*data) : 0;
  return fbs::CreateBuffer(
      _fbb,
      data__,
      size);
}

::flatbuffers::Offset<Buffer> CreateBuffer(::flatbuffers::FlatBufferBuilder &_fbb, const BufferT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ArgumentRefT : public ::flatbuffers::NativeTable {
  typedef ArgumentRef TableType;
  uint32_t arg_index = 0;
  uint32_t source_buffer = 0;
  uint32_t source_offset = 0;
};

struct ArgumentRef FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ArgumentRefT NativeTableType;
  typedef ArgumentRefBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ARG_INDEX = 4,
    VT_SOURCE_BUFFER = 6,
    VT_SOURCE_OFFSET = 8
  };
  uint32_t arg_index() const {
    return GetField<uint32_t>(VT_ARG_INDEX, 0);
  }
  uint32_t source_buffer() const {
    return GetField<uint32_t>(VT_SOURCE_BUFFER, 0);
  }
  uint32_t source_offset() const {
    return GetField<uint32_t>(VT_SOURCE_OFFSET, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ARG_INDEX, 4) &&
           VerifyField<uint32_t>(verifier, VT_SOURCE_BUFFER, 4) &&
           VerifyField<uint32_t>(verifier, VT_SOURCE_OFFSET, 4) &&
           verifier.EndTable();
  }
  ArgumentRefT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ArgumentRefT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ArgumentRef> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ArgumentRefT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ArgumentRefBuilder {
  typedef ArgumentRef Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_arg_index(uint32_t arg_index) {
    fbb_.AddElement<uint32_t>(ArgumentRef::VT_ARG_INDEX, arg_index, 0);
  }
  void add_source_buffer(uint32_t source_buffer) {
    fbb_.AddElement<uint32_t>(ArgumentRef::VT_SOURCE_BUFFER, source_buffer, 0);
  }
  void add_source_offset(uint32_t source_offset) {
    fbb_.AddElement<uint32_t>(ArgumentRef::VT_SOURCE_OFFSET, source_offset, 0);
  }
  explicit ArgumentRefBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ArgumentRef> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ArgumentRef>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ArgumentRef> CreateArgumentRef(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t arg_index = 0,
    uint32_t source_buffer = 0,
    uint32_t source_offset = 0) {
  ArgumentRefBuilder builder_(_fbb);
  builder_.add_source_offset(source_offset);
  builder_.add_source_buffer(source_buffer);
  builder_.add_arg_index(arg_index);
  return builder_.Finish();
}

::flatbuffers::Offset<ArgumentRef> CreateArgumentRef(::flatbuffers::FlatBufferBuilder &_fbb, const ArgumentRefT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct PatchRefT : public ::flatbuffers::NativeTable {
  typedef PatchRef TableType;
  uint32_t target_buffer = 0;
  uint32_t target_offset = 0;
  uint32_t source_buffer = 0;
  uint32_t source_offset = 0;
};

struct PatchRef FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PatchRefT NativeTableType;
  typedef PatchRefBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TARGET_BUFFER = 4,
    VT_TARGET_OFFSET = 6,
    VT_SOURCE_BUFFER = 8,
    VT_SOURCE_OFFSET = 10
  };
  uint32_t target_buffer() const {
    return GetField<uint32_t>(VT_TARGET_BUFFER, 0);
  }
  uint32_t target_offset() const {
    return GetField<uint32_t>(VT_TARGET_OFFSET, 0);
  }
  uint32_t source_buffer() const {
    return GetField<uint32_t>(VT_SOURCE_BUFFER, 0);
  }
  uint32_t source_offset() const {
    return GetField<uint32_t>(VT_SOURCE_OFFSET, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_TARGET_BUFFER, 4) &&
           VerifyField<uint32_t>(verifier, VT_TARGET_OFFSET, 4) &&
           VerifyField<uint32_t>(verifier, VT_SOURCE_BUFFER, 4) &&
           VerifyField<uint32_t>(verifier, VT_SOURCE_OFFSET, 4) &&
           verifier.EndTable();
  }
  PatchRefT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(PatchRefT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<PatchRef> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PatchRefT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct PatchRefBuilder {
  typedef PatchRef Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_target_buffer(uint32_t target_buffer) {
    fbb_.AddElement<uint32_t>(PatchRef::VT_TARGET_BUFFER, target_buffer, 0);
  }
  void add_target_offset(uint32_t target_offset) {
    fbb_.AddElement<uint32_t>(PatchRef::VT_TARGET_OFFSET, target_offset, 0);
  }
  void add_source_buffer(uint32_t source_buffer) {
    fbb_.AddElement<uint32_t>(PatchRef::VT_SOURCE_BUFFER, source_buffer, 0);
  }
  void add_source_offset(uint32_t source_offset) {
    fbb_.AddElement<uint32_t>(PatchRef::VT_SOURCE_OFFSET, source_offset, 0);
  }
  explicit PatchRefBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PatchRef> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PatchRef>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PatchRef> CreatePatchRef(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t target_buffer = 0,
    uint32_t target_offset = 0,
    uint32_t source_buffer = 0,
    uint32_t source_offset = 0) {
  PatchRefBuilder builder_(_fbb);
  builder_.add_source_offset(source_offset);
  builder_.add_source_buffer(source_buffer);
  builder_.add_target_offset(target_offset);
  builder_.add_target_buffer(target_buffer);
  return builder_.Finish();
}

::flatbuffers::Offset<PatchRef> CreatePatchRef(::flatbuffers::FlatBufferBuilder &_fbb, const PatchRefT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ImmediateTriggerT : public ::flatbuffers::NativeTable {
  typedef ImmediateTrigger TableType;
};

struct ImmediateTrigger FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ImmediateTriggerT NativeTableType;
  typedef ImmediateTriggerBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
  ImmediateTriggerT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ImmediateTriggerT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ImmediateTrigger> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ImmediateTriggerT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ImmediateTriggerBuilder {
  typedef ImmediateTrigger Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit ImmediateTriggerBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ImmediateTrigger> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ImmediateTrigger>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ImmediateTrigger> CreateImmediateTrigger(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  ImmediateTriggerBuilder builder_(_fbb);
  return builder_.Finish();
}

::flatbuffers::Offset<ImmediateTrigger> CreateImmediateTrigger(::flatbuffers::FlatBufferBuilder &_fbb, const ImmediateTriggerT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct AfterDriverEntryTriggerT : public ::flatbuffers::NativeTable {
  typedef AfterDriverEntryTrigger TableType;
};

struct AfterDriverEntryTrigger FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AfterDriverEntryTriggerT NativeTableType;
  typedef AfterDriverEntryTriggerBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
  AfterDriverEntryTriggerT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(AfterDriverEntryTriggerT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<AfterDriverEntryTrigger> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const AfterDriverEntryTriggerT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct AfterDriverEntryTriggerBuilder {
  typedef AfterDriverEntryTrigger Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit AfterDriverEntryTriggerBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AfterDriverEntryTrigger> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AfterDriverEntryTrigger>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AfterDriverEntryTrigger> CreateAfterDriverEntryTrigger(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  AfterDriverEntryTriggerBuilder builder_(_fbb);
  return builder_.Finish();
}

::flatbuffers::Offset<AfterDriverEntryTrigger> CreateAfterDriverEntryTrigger(::flatbuffers::FlatBufferBuilder &_fbb, const AfterDriverEntryTriggerT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CallTargetT : public ::flatbuffers::NativeTable {
  typedef CallTarget TableType;
  std::string function{};
};

struct CallTarget FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CallTargetT NativeTableType;
  typedef CallTargetBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FUNCTION = 4
  };
  const ::flatbuffers::String *function() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FUNCTION);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_FUNCTION) &&
           verifier.VerifyString(function()) &&
           verifier.EndTable();
  }
  CallTargetT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CallTargetT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CallTarget> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CallTargetT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CallTargetBuilder {
  typedef CallTarget Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_function(::flatbuffers::Offset<::flatbuffers::String> function) {
    fbb_.AddOffset(CallTarget::VT_FUNCTION, function);
  }
  explicit CallTargetBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CallTarget> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CallTarget>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CallTarget> CreateCallTarget(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> function = 0) {
  CallTargetBuilder builder_(_fbb);
  builder_.add_function(function);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CallTarget> CreateCallTargetDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *function = nullptr) {
  auto function__ = function ? _fbb.CreateString(function) : 0;
  return fbs::CreateCallTarget(
      _fbb,
      function__);
}

::flatbuffers::Offset<CallTarget> CreateCallTarget(::flatbuffers::FlatBufferBuilder &_fbb, const CallTargetT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct IoctlTargetT : public ::flatbuffers::NativeTable {
  typedef IoctlTarget TableType;
  uint32_t code = 0;
  uint32_t output_size = 0;
};

struct IoctlTarget FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef IoctlTargetT NativeTableType;
  typedef IoctlTargetBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CODE = 4,
    VT_OUTPUT_SIZE = 6
  };
  uint32_t code() const {
    return GetField<uint32_t>(VT_CODE, 0);
  }
  uint32_t output_size() const {
    return GetField<uint32_t>(VT_OUTPUT_SIZE, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_CODE, 4) &&
           VerifyField<uint32_t>(verifier, VT_OUTPUT_SIZE, 4) &&
           verifier.EndTable();
  }
  IoctlTargetT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(IoctlTargetT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<IoctlTarget> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const IoctlTargetT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct IoctlTargetBuilder {
  typedef IoctlTarget Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_code(uint32_t code) {
    fbb_.AddElement<uint32_t>(IoctlTarget::VT_CODE, code, 0);
  }
  void add_output_size(uint32_t output_size) {
    fbb_.AddElement<uint32_t>(IoctlTarget::VT_OUTPUT_SIZE, output_size, 0);
  }
  explicit IoctlTargetBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<IoctlTarget> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<IoctlTarget>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<IoctlTarget> CreateIoctlTarget(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t code = 0,
    uint32_t output_size = 0) {
  IoctlTargetBuilder builder_(_fbb);
  builder_.add_output_size(output_size);
  builder_.add_code(code);
  return builder_.Finish();
}

::flatbuffers::Offset<IoctlTarget> CreateIoctlTarget(::flatbuffers::FlatBufferBuilder &_fbb, const IoctlTargetT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct EventT : public ::flatbuffers::NativeTable {
  typedef Event TableType;
  std::string description{};
  fbs::TargetUnion target{};
  std::vector<uint64_t> arguments{};
  std::vector<std::unique_ptr<fbs::BufferT>> buffers{};
  std::vector<fbs::BufferRefUnion> buffer_refs{};
  fbs::TriggerUnion trigger{};
  EventT() = default;
  EventT(const EventT &o);
  EventT(EventT&&) FLATBUFFERS_NOEXCEPT = default;
  EventT &operator=(EventT o) FLATBUFFERS_NOEXCEPT;
};

struct Event FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EventT NativeTableType;
  typedef EventBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DESCRIPTION = 4,
    VT_TARGET_TYPE = 6,
    VT_TARGET = 8,
    VT_ARGUMENTS = 10,
    VT_BUFFERS = 12,
    VT_BUFFER_REFS_TYPE = 14,
    VT_BUFFER_REFS = 16,
    VT_TRIGGER_TYPE = 18,
    VT_TRIGGER = 20
  };
  const ::flatbuffers::String *description() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DESCRIPTION);
  }
  fbs::Target target_type() const {
    return static_cast<fbs::Target>(GetField<uint8_t>(VT_TARGET_TYPE, 0));
  }
  const void *target() const {
    return GetPointer<const void *>(VT_TARGET);
  }
  template<typename T> const T *target_as() const;
  const fbs::CallTarget *target_as_CallTarget() const {
    return target_type() == fbs::Target::CallTarget ? static_cast<const fbs::CallTarget *>(target()) : nullptr;
  }
  const fbs::IoctlTarget *target_as_IoctlTarget() const {
    return target_type() == fbs::Target::IoctlTarget ? static_cast<const fbs::IoctlTarget *>(target()) : nullptr;
  }
  const ::flatbuffers::Vector<uint64_t> *arguments() const {
    return GetPointer<const ::flatbuffers::Vector<uint64_t> *>(VT_ARGUMENTS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<fbs::Buffer>> *buffers() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<fbs::Buffer>> *>(VT_BUFFERS);
  }
  const ::flatbuffers::Vector<fbs::BufferRef> *buffer_refs_type() const {
    return GetPointer<const ::flatbuffers::Vector<fbs::BufferRef> *>(VT_BUFFER_REFS_TYPE);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *buffer_refs() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *>(VT_BUFFER_REFS);
  }
  fbs::Trigger trigger_type() const {
    return static_cast<fbs::Trigger>(GetField<uint8_t>(VT_TRIGGER_TYPE, 0));
  }
  const void *trigger() const {
    return GetPointer<const void *>(VT_TRIGGER);
  }
  template<typename T> const T *trigger_as() const;
  const fbs::ImmediateTrigger *trigger_as_ImmediateTrigger() const {
    return trigger_type() == fbs::Trigger::ImmediateTrigger ? static_cast<const fbs::ImmediateTrigger *>(trigger()) : nullptr;
  }
  const fbs::AfterDriverEntryTrigger *trigger_as_AfterDriverEntryTrigger() const {
    return trigger_type() == fbs::Trigger::AfterDriverEntryTrigger ? static_cast<const fbs::AfterDriverEntryTrigger *>(trigger()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DESCRIPTION) &&
           verifier.VerifyString(description()) &&
           VerifyField<uint8_t>(verifier, VT_TARGET_TYPE, 1) &&
           VerifyOffset(verifier, VT_TARGET) &&
           VerifyTarget(verifier, target(), target_type()) &&
           VerifyOffset(verifier, VT_ARGUMENTS) &&
           verifier.VerifyVector(arguments()) &&
           VerifyOffset(verifier, VT_BUFFERS) &&
           verifier.VerifyVector(buffers()) &&
           verifier.VerifyVectorOfTables(buffers()) &&
           VerifyOffset(verifier, VT_BUFFER_REFS_TYPE) &&
           verifier.VerifyVector(buffer_refs_type()) &&
           VerifyOffset(verifier, VT_BUFFER_REFS) &&
           verifier.VerifyVector(buffer_refs()) &&
           VerifyBufferRefVector(verifier, buffer_refs(), buffer_refs_type()) &&
           VerifyField<uint8_t>(verifier, VT_TRIGGER_TYPE, 1) &&
           VerifyOffset(verifier, VT_TRIGGER) &&
           VerifyTrigger(verifier, trigger(), trigger_type()) &&
           verifier.EndTable();
  }
  EventT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(EventT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Event> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const EventT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

template<> inline const fbs::CallTarget *Event::target_as<fbs::CallTarget>() const {
  return target_as_CallTarget();
}

template<> inline const fbs::IoctlTarget *Event::target_as<fbs::IoctlTarget>() const {
  return target_as_IoctlTarget();
}

template<> inline const fbs::ImmediateTrigger *Event::trigger_as<fbs::ImmediateTrigger>() const {
  return trigger_as_ImmediateTrigger();
}

template<> inline const fbs::AfterDriverEntryTrigger *Event::trigger_as<fbs::AfterDriverEntryTrigger>() const {
  return trigger_as_AfterDriverEntryTrigger();
}

struct EventBuilder {
  typedef Event Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_description(::flatbuffers::Offset<::flatbuffers::String> description) {
    fbb_.AddOffset(Event::VT_DESCRIPTION, description);
  }
  void add_target_type(fbs::Target target_type) {
    fbb_.AddElement<uint8_t>(Event::VT_TARGET_TYPE, static_cast<uint8_t>(target_type), 0);
  }
  void add_target(::flatbuffers::Offset<void> target) {
    fbb_.AddOffset(Event::VT_TARGET, target);
  }
  void add_arguments(::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> arguments) {
    fbb_.AddOffset(Event::VT_ARGUMENTS, arguments);
  }
  void add_buffers(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbs::Buffer>>> buffers) {
    fbb_.AddOffset(Event::VT_BUFFERS, buffers);
  }
  void add_buffer_refs_type(::flatbuffers::Offset<::flatbuffers::Vector<fbs::BufferRef>> buffer_refs_type) {
    fbb_.AddOffset(Event::VT_BUFFER_REFS_TYPE, buffer_refs_type);
  }
  void add_buffer_refs(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<void>>> buffer_refs) {
    fbb_.AddOffset(Event::VT_BUFFER_REFS, buffer_refs);
  }
  void add_trigger_type(fbs::Trigger trigger_type) {
    fbb_.AddElement<uint8_t>(Event::VT_TRIGGER_TYPE, static_cast<uint8_t>(trigger_type), 0);
  }
  void add_trigger(::flatbuffers::Offset<void> trigger) {
    fbb_.AddOffset(Event::VT_TRIGGER, trigger);
  }
  explicit EventBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Event> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Event>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Event> CreateEvent(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> description = 0,
    fbs::Target target_type = fbs::Target::NONE,
    ::flatbuffers::Offset<void> target = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> arguments = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbs::Buffer>>> buffers = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<fbs::BufferRef>> buffer_refs_type = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<void>>> buffer_refs = 0,
    fbs::Trigger trigger_type = fbs::Trigger::NONE,
    ::flatbuffers::Offset<void> trigger = 0) {
  EventBuilder builder_(_fbb);
  builder_.add_trigger(trigger);
  builder_.add_buffer_refs(buffer_refs);
  builder_.add_buffer_refs_type(buffer_refs_type);
  builder_.add_buffers(buffers);
  builder_.add_arguments(arguments);
  builder_.add_target(target);
  builder_.add_description(description);
  builder_.add_trigger_type(trigger_type);
  builder_.add_target_type(target_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Event> CreateEventDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *description = nullptr,
    fbs::Target target_type = fbs::Target::NONE,
    ::flatbuffers::Offset<void> target = 0,
    const std::vector<uint64_t> *arguments = nullptr,
    const std::vector<::flatbuffers::Offset<fbs::Buffer>> *buffers = nullptr,
    const std::vector<fbs::BufferRef> *buffer_refs_type = nullptr,
    const std::vector<::flatbuffers::Offset<void>> *buffer_refs = nullptr,
    fbs::Trigger trigger_type = fbs::Trigger::NONE,
    ::flatbuffers::Offset<void> trigger = 0) {
  auto description__ = description ? _fbb.CreateString(description) : 0;
  auto arguments__ = arguments ? _fbb.CreateVector<uint64_t>(*arguments) : 0;
  auto buffers__ = buffers ? _fbb.CreateVector<::flatbuffers::Offset<fbs::Buffer>>(*buffers) : 0;
  auto buffer_refs_type__ = buffer_refs_type ? _fbb.CreateVector<fbs::BufferRef>(*buffer_refs_type) : 0;
  auto buffer_refs__ = buffer_refs ? _fbb.CreateVector<::flatbuffers::Offset<void>>(*buffer_refs) : 0;
  return fbs::CreateEvent(
      _fbb,
      description__,
      target_type,
      target,
      arguments__,
      buffers__,
      buffer_refs_type__,
      buffer_refs__,
      trigger_type,
      trigger);
}

::flatbuffers::Offset<Event> CreateEvent(::flatbuffers::FlatBufferBuilder &_fbb, const EventT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct EventResultT : public ::flatbuffers::NativeTable {
  typedef EventResult TableType;
  uint64_t return_value = 0;
  bool succeeded = false;
  std::vector<std::unique_ptr<fbs::ModifiedBufferT>> modified_buffers{};
  EventResultT() = default;
  EventResultT(const EventResultT &o);
  EventResultT(EventResultT&&) FLATBUFFERS_NOEXCEPT = default;
  EventResultT &operator=(EventResultT o) FLATBUFFERS_NOEXCEPT;
};

struct EventResult FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EventResultT NativeTableType;
  typedef EventResultBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RETURN_VALUE = 4,
    VT_SUCCEEDED = 6,
    VT_MODIFIED_BUFFERS = 8
  };
  uint64_t return_value() const {
    return GetField<uint64_t>(VT_RETURN_VALUE, 0);
  }
  bool succeeded() const {
    return GetField<uint8_t>(VT_SUCCEEDED, 0) != 0;
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<fbs::ModifiedBuffer>> *modified_buffers() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<fbs::ModifiedBuffer>> *>(VT_MODIFIED_BUFFERS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_RETURN_VALUE, 8) &&
           VerifyField<uint8_t>(verifier, VT_SUCCEEDED, 1) &&
           VerifyOffset(verifier, VT_MODIFIED_BUFFERS) &&
           verifier.VerifyVector(modified_buffers()) &&
           verifier.VerifyVectorOfTables(modified_buffers()) &&
           verifier.EndTable();
  }
  EventResultT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(EventResultT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<EventResult> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const EventResultT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct EventResultBuilder {
  typedef EventResult Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_return_value(uint64_t return_value) {
    fbb_.AddElement<uint64_t>(EventResult::VT_RETURN_VALUE, return_value, 0);
  }
  void add_succeeded(bool succeeded) {
    fbb_.AddElement<uint8_t>(EventResult::VT_SUCCEEDED, static_cast<uint8_t>(succeeded), 0);
  }
  void add_modified_buffers(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbs::ModifiedBuffer>>> modified_buffers) {
    fbb_.AddOffset(EventResult::VT_MODIFIED_BUFFERS, modified_buffers);
  }
  explicit EventResultBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EventResult> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EventResult>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EventResult> CreateEventResult(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t return_value = 0,
    bool succeeded = false,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbs::ModifiedBuffer>>> modified_buffers = 0) {
  EventResultBuilder builder_(_fbb);
  builder_.add_return_value(return_value);
  builder_.add_modified_buffers(modified_buffers);
  builder_.add_succeeded(succeeded);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<EventResult> CreateEventResultDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t return_value = 0,
    bool succeeded = false,
    const std::vector<::flatbuffers::Offset<fbs::ModifiedBuffer>> *modified_buffers = nullptr) {
  auto modified_buffers__ = modified_buffers ? _fbb.CreateVector<::flatbuffers::Offset<fbs::ModifiedBuffer>>(*modified_buffers) : 0;
  return fbs::CreateEventResult(
      _fbb,
      return_value,
      succeeded,
      modified_buffers__);
}

::flatbuffers::Offset<EventResult> CreateEventResult(::flatbuffers::FlatBufferBuilder &_fbb, const EventResultT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ModifiedBufferT : public ::flatbuffers::NativeTable {
  typedef ModifiedBuffer TableType;
  uint32_t index = 0;
  std::vector<uint8_t> data{};
};

struct ModifiedBuffer FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ModifiedBufferT NativeTableType;
  typedef ModifiedBufferBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_INDEX = 4,
    VT_DATA = 6
  };
  uint32_t index() const {
    return GetField<uint32_t>(VT_INDEX, 0);
  }
  const ::flatbuffers::Vector<uint8_t> *data() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_DATA);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_INDEX, 4) &&
           VerifyOffset(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           verifier.EndTable();
  }
  ModifiedBufferT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ModifiedBufferT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ModifiedBuffer> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ModifiedBufferT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ModifiedBufferBuilder {
  typedef ModifiedBuffer Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_index(uint32_t index) {
    fbb_.AddElement<uint32_t>(ModifiedBuffer::VT_INDEX, index, 0);
  }
  void add_data(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data) {
    fbb_.AddOffset(ModifiedBuffer::VT_DATA, data);
  }
  explicit ModifiedBufferBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ModifiedBuffer> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ModifiedBuffer>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ModifiedBuffer> CreateModifiedBuffer(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t index = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data = 0) {
  ModifiedBufferBuilder builder_(_fbb);
  builder_.add_data(data);
  builder_.add_index(index);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ModifiedBuffer> CreateModifiedBufferDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t index = 0,
    const std::vector<uint8_t> *data = nullptr) {
  auto data__ = data ? _fbb.CreateVector<uint8_t>(*data) : 0;
  return fbs::CreateModifiedBuffer(
      _fbb,
      index,
      data__);
}

::flatbuffers::Offset<ModifiedBuffer> CreateModifiedBuffer(::flatbuffers::FlatBufferBuilder &_fbb, const ModifiedBufferT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ResultSequenceT : public ::flatbuffers::NativeTable {
  typedef ResultSequence TableType;
  std::vector<std::unique_ptr<fbs::EventResultT>> results{};
  ResultSequenceT() = default;
  ResultSequenceT(const ResultSequenceT &o);
  ResultSequenceT(ResultSequenceT&&) FLATBUFFERS_NOEXCEPT = default;
  ResultSequenceT &operator=(ResultSequenceT o) FLATBUFFERS_NOEXCEPT;
};

struct ResultSequence FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ResultSequenceT NativeTableType;
  typedef ResultSequenceBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RESULTS = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<fbs::EventResult>> *results() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<fbs::EventResult>> *>(VT_RESULTS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_RESULTS) &&
           verifier.VerifyVector(results()) &&
           verifier.VerifyVectorOfTables(results()) &&
           verifier.EndTable();
  }
  ResultSequenceT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ResultSequenceT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ResultSequence> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ResultSequenceT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ResultSequenceBuilder {
  typedef ResultSequence Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_results(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbs::EventResult>>> results) {
    fbb_.AddOffset(ResultSequence::VT_RESULTS, results);
  }
  explicit ResultSequenceBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ResultSequence> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ResultSequence>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ResultSequence> CreateResultSequence(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbs::EventResult>>> results = 0) {
  ResultSequenceBuilder builder_(_fbb);
  builder_.add_results(results);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ResultSequence> CreateResultSequenceDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<fbs::EventResult>> *results = nullptr) {
  auto results__ = results ? _fbb.CreateVector<::flatbuffers::Offset<fbs::EventResult>>(*results) : 0;
  return fbs::CreateResultSequence(
      _fbb,
      results__);
}

::flatbuffers::Offset<ResultSequence> CreateResultSequence(::flatbuffers::FlatBufferBuilder &_fbb, const ResultSequenceT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline BufferT *Buffer::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<BufferT>(new BufferT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Buffer::UnPackTo(BufferT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = data(); if (_e) { _o->data.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->data.begin()); } }
  { auto _e = size(); _o->size = _e; }
}

inline ::flatbuffers::Offset<Buffer> Buffer::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BufferT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateBuffer(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Buffer> CreateBuffer(::flatbuffers::FlatBufferBuilder &_fbb, const BufferT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const BufferT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _data = _o->data.size() ? _fbb.CreateVector(_o->data) : 0;
  auto _size = _o->size;
  return fbs::CreateBuffer(
      _fbb,
      _data,
      _size);
}

inline ArgumentRefT *ArgumentRef::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ArgumentRefT>(new ArgumentRefT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ArgumentRef::UnPackTo(ArgumentRefT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = arg_index(); _o->arg_index = _e; }
  { auto _e = source_buffer(); _o->source_buffer = _e; }
  { auto _e = source_offset(); _o->source_offset = _e; }
}

inline ::flatbuffers::Offset<ArgumentRef> ArgumentRef::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ArgumentRefT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateArgumentRef(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ArgumentRef> CreateArgumentRef(::flatbuffers::FlatBufferBuilder &_fbb, const ArgumentRefT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ArgumentRefT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _arg_index = _o->arg_index;
  auto _source_buffer = _o->source_buffer;
  auto _source_offset = _o->source_offset;
  return fbs::CreateArgumentRef(
      _fbb,
      _arg_index,
      _source_buffer,
      _source_offset);
}

inline PatchRefT *PatchRef::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<PatchRefT>(new PatchRefT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void PatchRef::UnPackTo(PatchRefT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = target_buffer(); _o->target_buffer = _e; }
  { auto _e = target_offset(); _o->target_offset = _e; }
  { auto _e = source_buffer(); _o->source_buffer = _e; }
  { auto _e = source_offset(); _o->source_offset = _e; }
}

inline ::flatbuffers::Offset<PatchRef> PatchRef::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PatchRefT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreatePatchRef(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<PatchRef> CreatePatchRef(::flatbuffers::FlatBufferBuilder &_fbb, const PatchRefT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const PatchRefT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _target_buffer = _o->target_buffer;
  auto _target_offset = _o->target_offset;
  auto _source_buffer = _o->source_buffer;
  auto _source_offset = _o->source_offset;
  return fbs::CreatePatchRef(
      _fbb,
      _target_buffer,
      _target_offset,
      _source_buffer,
      _source_offset);
}

inline ImmediateTriggerT *ImmediateTrigger::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ImmediateTriggerT>(new ImmediateTriggerT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ImmediateTrigger::UnPackTo(ImmediateTriggerT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
}

inline ::flatbuffers::Offset<ImmediateTrigger> ImmediateTrigger::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ImmediateTriggerT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateImmediateTrigger(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ImmediateTrigger> CreateImmediateTrigger(::flatbuffers::FlatBufferBuilder &_fbb, const ImmediateTriggerT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ImmediateTriggerT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  return fbs::CreateImmediateTrigger(
      _fbb);
}

inline AfterDriverEntryTriggerT *AfterDriverEntryTrigger::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<AfterDriverEntryTriggerT>(new AfterDriverEntryTriggerT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void AfterDriverEntryTrigger::UnPackTo(AfterDriverEntryTriggerT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
}

inline ::flatbuffers::Offset<AfterDriverEntryTrigger> AfterDriverEntryTrigger::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const AfterDriverEntryTriggerT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateAfterDriverEntryTrigger(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<AfterDriverEntryTrigger> CreateAfterDriverEntryTrigger(::flatbuffers::FlatBufferBuilder &_fbb, const AfterDriverEntryTriggerT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const AfterDriverEntryTriggerT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  return fbs::CreateAfterDriverEntryTrigger(
      _fbb);
}

inline CallTargetT *CallTarget::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CallTargetT>(new CallTargetT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CallTarget::UnPackTo(CallTargetT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = function(); if (_e) _o->function = _e->str(); }
}

inline ::flatbuffers::Offset<CallTarget> CallTarget::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CallTargetT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateCallTarget(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CallTarget> CreateCallTarget(::flatbuffers::FlatBufferBuilder &_fbb, const CallTargetT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CallTargetT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _function = _o->function.empty() ? 0 : _fbb.CreateString(_o->function);
  return fbs::CreateCallTarget(
      _fbb,
      _function);
}

inline IoctlTargetT *IoctlTarget::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<IoctlTargetT>(new IoctlTargetT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void IoctlTarget::UnPackTo(IoctlTargetT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = code(); _o->code = _e; }
  { auto _e = output_size(); _o->output_size = _e; }
}

inline ::flatbuffers::Offset<IoctlTarget> IoctlTarget::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const IoctlTargetT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateIoctlTarget(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<IoctlTarget> CreateIoctlTarget(::flatbuffers::FlatBufferBuilder &_fbb, const IoctlTargetT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const IoctlTargetT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _code = _o->code;
  auto _output_size = _o->output_size;
  return fbs::CreateIoctlTarget(
      _fbb,
      _code,
      _output_size);
}

inline EventT::EventT(const EventT &o)
      : description(o.description),
        target(o.target),
        arguments(o.arguments),
        buffer_refs(o.buffer_refs),
        trigger(o.trigger) {
  buffers.reserve(o.buffers.size());
  for (const auto &buffers_ : o.buffers) { buffers.emplace_back((buffers_) ? new fbs::BufferT(*buffers_) : nullptr); }
}

inline EventT &EventT::operator=(EventT o) FLATBUFFERS_NOEXCEPT {
  std::swap(description, o.description);
  std::swap(target, o.target);
  std::swap(arguments, o.arguments);
  std::swap(buffers, o.buffers);
  std::swap(buffer_refs, o.buffer_refs);
  std::swap(trigger, o.trigger);
  return *this;
}

inline EventT *Event::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<EventT>(new EventT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Event::UnPackTo(EventT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = description(); if (_e) _o->description = _e->str(); }
  { auto _e = target_type(); _o->target.type = _e; }
  { auto _e = target(); if (_e) _o->target.value = fbs::TargetUnion::UnPack(_e, target_type(), _resolver); }
  { auto _e = arguments(); if (_e) { _o->arguments.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->arguments[_i] = _e->Get(_i); } } else { _o->arguments.resize(0); } }
  { auto _e = buffers(); if (_e) { _o->buffers.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->buffers[_i]) { _e->Get(_i)->UnPackTo(_o->buffers[_i].get(), _resolver); } else { _o->buffers[_i] = std::unique_ptr<fbs::BufferT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->buffers.resize(0); } }
  { auto _e = buffer_refs_type(); if (_e) { _o->buffer_refs.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->buffer_refs[_i].type = static_cast<fbs::BufferRef>(_e->Get(_i)); } } else { _o->buffer_refs.resize(0); } }
  { auto _e = buffer_refs(); if (_e) { _o->buffer_refs.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->buffer_refs[_i].value = fbs::BufferRefUnion::UnPack(_e->Get(_i), buffer_refs_type()->GetEnum<BufferRef>(_i), _resolver); } } else { _o->buffer_refs.resize(0); } }
  { auto _e = trigger_type(); _o->trigger.type = _e; }
  { auto _e = trigger(); if (_e) _o->trigger.value = fbs::TriggerUnion::UnPack(_e, trigger_type(), _resolver); }
}

inline ::flatbuffers::Offset<Event> Event::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const EventT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateEvent(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Event> CreateEvent(::flatbuffers::FlatBufferBuilder &_fbb, const EventT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const EventT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _description = _o->description.empty() ? 0 : _fbb.CreateString(_o->description);
  auto _target_type = _o->target.type;
  auto _target = _o->target.Pack(_fbb);
  auto _arguments = _o->arguments.size() ? _fbb.CreateVector(_o->arguments) : 0;
  auto _buffers = _o->buffers.size() ? _fbb.CreateVector<::flatbuffers::Offset<fbs::Buffer>> (_o->buffers.size(), [](size_t i, _VectorArgs *__va) { return CreateBuffer(*__va->__fbb, __va->__o->buffers[i].get(), __va->__rehasher); }, &_va ) : 0;
  auto _buffer_refs_type = _o->buffer_refs.size() ? _fbb.CreateVector<BufferRef>(_o->buffer_refs.size(), [](size_t i, _VectorArgs *__va) { return __va->__o->buffer_refs[i].type; }, &_va) : 0;
  auto _buffer_refs = _o->buffer_refs.size() ? _fbb.CreateVector<::flatbuffers::Offset<void>>(_o->buffer_refs.size(), [](size_t i, _VectorArgs *__va) { return __va->__o->buffer_refs[i].Pack(*__va->__fbb, __va->__rehasher); }, &_va) : 0;
  auto _trigger_type = _o->trigger.type;
  auto _trigger = _o->trigger.Pack(_fbb);
  return fbs::CreateEvent(
      _fbb,
      _description,
      _target_type,
      _target,
      _arguments,
      _buffers,
      _buffer_refs_type,
      _buffer_refs,
      _trigger_type,
      _trigger);
}

inline EventResultT::EventResultT(const EventResultT &o)
      : return_value(o.return_value),
        succeeded(o.succeeded) {
  modified_buffers.reserve(o.modified_buffers.size());
  for (const auto &modified_buffers_ : o.modified_buffers) { modified_buffers.emplace_back((modified_buffers_) ? new fbs::ModifiedBufferT(*modified_buffers_) : nullptr); }
}

inline EventResultT &EventResultT::operator=(EventResultT o) FLATBUFFERS_NOEXCEPT {
  std::swap(return_value, o.return_value);
  std::swap(succeeded, o.succeeded);
  std::swap(modified_buffers, o.modified_buffers);
  return *this;
}

inline EventResultT *EventResult::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<EventResultT>(new EventResultT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void EventResult::UnPackTo(EventResultT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = return_value(); _o->return_value = _e; }
  { auto _e = succeeded(); _o->succeeded = _e; }
  { auto _e = modified_buffers(); if (_e) { _o->modified_buffers.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->modified_buffers[_i]) { _e->Get(_i)->UnPackTo(_o->modified_buffers[_i].get(), _resolver); } else { _o->modified_buffers[_i] = std::unique_ptr<fbs::ModifiedBufferT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->modified_buffers.resize(0); } }
}

inline ::flatbuffers::Offset<EventResult> EventResult::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const EventResultT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateEventResult(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<EventResult> CreateEventResult(::flatbuffers::FlatBufferBuilder &_fbb, const EventResultT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const EventResultT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _return_value = _o->return_value;
  auto _succeeded = _o->succeeded;
  auto _modified_buffers = _o->modified_buffers.size() ? _fbb.CreateVector<::flatbuffers::Offset<fbs::ModifiedBuffer>> (_o->modified_buffers.size(), [](size_t i, _VectorArgs *__va) { return CreateModifiedBuffer(*__va->__fbb, __va->__o->modified_buffers[i].get(), __va->__rehasher); }, &_va ) : 0;
  return fbs::CreateEventResult(
      _fbb,
      _return_value,
      _succeeded,
      _modified_buffers);
}

inline ModifiedBufferT *ModifiedBuffer::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ModifiedBufferT>(new ModifiedBufferT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ModifiedBuffer::UnPackTo(ModifiedBufferT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = index(); _o->index = _e; }
  { auto _e = data(); if (_e) { _o->data.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->data.begin()); } }
}

inline ::flatbuffers::Offset<ModifiedBuffer> ModifiedBuffer::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ModifiedBufferT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateModifiedBuffer(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ModifiedBuffer> CreateModifiedBuffer(::flatbuffers::FlatBufferBuilder &_fbb, const ModifiedBufferT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ModifiedBufferT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _index = _o->index;
  auto _data = _o->data.size() ? _fbb.CreateVector(_o->data) : 0;
  return fbs::CreateModifiedBuffer(
      _fbb,
      _index,
      _data);
}

inline ResultSequenceT::ResultSequenceT(const ResultSequenceT &o) {
  results.reserve(o.results.size());
  for (const auto &results_ : o.results) { results.emplace_back((results_) ? new fbs::EventResultT(*results_) : nullptr); }
}

inline ResultSequenceT &ResultSequenceT::operator=(ResultSequenceT o) FLATBUFFERS_NOEXCEPT {
  std::swap(results, o.results);
  return *this;
}

inline ResultSequenceT *ResultSequence::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ResultSequenceT>(new ResultSequenceT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ResultSequence::UnPackTo(ResultSequenceT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = results(); if (_e) { _o->results.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->results[_i]) { _e->Get(_i)->UnPackTo(_o->results[_i].get(), _resolver); } else { _o->results[_i] = std::unique_ptr<fbs::EventResultT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->results.resize(0); } }
}

inline ::flatbuffers::Offset<ResultSequence> ResultSequence::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ResultSequenceT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateResultSequence(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ResultSequence> CreateResultSequence(::flatbuffers::FlatBufferBuilder &_fbb, const ResultSequenceT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ResultSequenceT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _results = _o->results.size() ? _fbb.CreateVector<::flatbuffers::Offset<fbs::EventResult>> (_o->results.size(), [](size_t i, _VectorArgs *__va) { return CreateEventResult(*__va->__fbb, __va->__o->results[i].get(), __va->__rehasher); }, &_va ) : 0;
  return fbs::CreateResultSequence(
      _fbb,
      _results);
}

inline bool VerifyBufferRef(::flatbuffers::Verifier &verifier, const void *obj, BufferRef type) {
  switch (type) {
    case BufferRef::NONE: {
      return true;
    }
    case BufferRef::ArgumentRef: {
      auto ptr = reinterpret_cast<const fbs::ArgumentRef *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case BufferRef::PatchRef: {
      auto ptr = reinterpret_cast<const fbs::PatchRef *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyBufferRefVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<BufferRef> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyBufferRef(
        verifier,  values->Get(i), types->GetEnum<BufferRef>(i))) {
      return false;
    }
  }
  return true;
}

inline void *BufferRefUnion::UnPack(const void *obj, BufferRef type, const ::flatbuffers::resolver_function_t *resolver) {
  (void)resolver;
  switch (type) {
    case BufferRef::ArgumentRef: {
      auto ptr = reinterpret_cast<const fbs::ArgumentRef *>(obj);
      return ptr->UnPack(resolver);
    }
    case BufferRef::PatchRef: {
      auto ptr = reinterpret_cast<const fbs::PatchRef *>(obj);
      return ptr->UnPack(resolver);
    }
    default: return nullptr;
  }
}

inline ::flatbuffers::Offset<void> BufferRefUnion::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher) const {
  (void)_rehasher;
  switch (type) {
    case BufferRef::ArgumentRef: {
      auto ptr = reinterpret_cast<const fbs::ArgumentRefT *>(value);
      return CreateArgumentRef(_fbb, ptr, _rehasher).Union();
    }
    case BufferRef::PatchRef: {
      auto ptr = reinterpret_cast<const fbs::PatchRefT *>(value);
      return CreatePatchRef(_fbb, ptr, _rehasher).Union();
    }
    default: return 0;
  }
}

inline BufferRefUnion::BufferRefUnion(const BufferRefUnion &u) : type(u.type), value(nullptr) {
  switch (type) {
    case BufferRef::ArgumentRef: {
      value = new fbs::ArgumentRefT(*reinterpret_cast<fbs::ArgumentRefT *>(u.value));
      break;
    }
    case BufferRef::PatchRef: {
      value = new fbs::PatchRefT(*reinterpret_cast<fbs::PatchRefT *>(u.value));
      break;
    }
    default:
      break;
  }
}

inline void BufferRefUnion::Reset() {
  switch (type) {
    case BufferRef::ArgumentRef: {
      auto ptr = reinterpret_cast<fbs::ArgumentRefT *>(value);
      delete ptr;
      break;
    }
    case BufferRef::PatchRef: {
      auto ptr = reinterpret_cast<fbs::PatchRefT *>(value);
      delete ptr;
      break;
    }
    default: break;
  }
  value = nullptr;
  type = BufferRef::NONE;
}

inline bool VerifyTrigger(::flatbuffers::Verifier &verifier, const void *obj, Trigger type) {
  switch (type) {
    case Trigger::NONE: {
      return true;
    }
    case Trigger::ImmediateTrigger: {
      auto ptr = reinterpret_cast<const fbs::ImmediateTrigger *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Trigger::AfterDriverEntryTrigger: {
      auto ptr = reinterpret_cast<const fbs::AfterDriverEntryTrigger *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyTriggerVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<Trigger> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyTrigger(
        verifier,  values->Get(i), types->GetEnum<Trigger>(i))) {
      return false;
    }
  }
  return true;
}

inline void *TriggerUnion::UnPack(const void *obj, Trigger type, const ::flatbuffers::resolver_function_t *resolver) {
  (void)resolver;
  switch (type) {
    case Trigger::ImmediateTrigger: {
      auto ptr = reinterpret_cast<const fbs::ImmediateTrigger *>(obj);
      return ptr->UnPack(resolver);
    }
    case Trigger::AfterDriverEntryTrigger: {
      auto ptr = reinterpret_cast<const fbs::AfterDriverEntryTrigger *>(obj);
      return ptr->UnPack(resolver);
    }
    default: return nullptr;
  }
}

inline ::flatbuffers::Offset<void> TriggerUnion::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher) const {
  (void)_rehasher;
  switch (type) {
    case Trigger::ImmediateTrigger: {
      auto ptr = reinterpret_cast<const fbs::ImmediateTriggerT *>(value);
      return CreateImmediateTrigger(_fbb, ptr, _rehasher).Union();
    }
    case Trigger::AfterDriverEntryTrigger: {
      auto ptr = reinterpret_cast<const fbs::AfterDriverEntryTriggerT *>(value);
      return CreateAfterDriverEntryTrigger(_fbb, ptr, _rehasher).Union();
    }
    default: return 0;
  }
}

inline TriggerUnion::TriggerUnion(const TriggerUnion &u) : type(u.type), value(nullptr) {
  switch (type) {
    case Trigger::ImmediateTrigger: {
      value = new fbs::ImmediateTriggerT(*reinterpret_cast<fbs::ImmediateTriggerT *>(u.value));
      break;
    }
    case Trigger::AfterDriverEntryTrigger: {
      value = new fbs::AfterDriverEntryTriggerT(*reinterpret_cast<fbs::AfterDriverEntryTriggerT *>(u.value));
      break;
    }
    default:
      break;
  }
}

inline void TriggerUnion::Reset() {
  switch (type) {
    case Trigger::ImmediateTrigger: {
      auto ptr = reinterpret_cast<fbs::ImmediateTriggerT *>(value);
      delete ptr;
      break;
    }
    case Trigger::AfterDriverEntryTrigger: {
      auto ptr = reinterpret_cast<fbs::AfterDriverEntryTriggerT *>(value);
      delete ptr;
      break;
    }
    default: break;
  }
  value = nullptr;
  type = Trigger::NONE;
}

inline bool VerifyTarget(::flatbuffers::Verifier &verifier, const void *obj, Target type) {
  switch (type) {
    case Target::NONE: {
      return true;
    }
    case Target::CallTarget: {
      auto ptr = reinterpret_cast<const fbs::CallTarget *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Target::IoctlTarget: {
      auto ptr = reinterpret_cast<const fbs::IoctlTarget *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyTargetVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<Target> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyTarget(
        verifier,  values->Get(i), types->GetEnum<Target>(i))) {
      return false;
    }
  }
  return true;
}

inline void *TargetUnion::UnPack(const void *obj, Target type, const ::flatbuffers::resolver_function_t *resolver) {
  (void)resolver;
  switch (type) {
    case Target::CallTarget: {
      auto ptr = reinterpret_cast<const fbs::CallTarget *>(obj);
      return ptr->UnPack(resolver);
    }
    case Target::IoctlTarget: {
      auto ptr = reinterpret_cast<const fbs::IoctlTarget *>(obj);
      return ptr->UnPack(resolver);
    }
    default: return nullptr;
  }
}

inline ::flatbuffers::Offset<void> TargetUnion::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher) const {
  (void)_rehasher;
  switch (type) {
    case Target::CallTarget: {
      auto ptr = reinterpret_cast<const fbs::CallTargetT *>(value);
      return CreateCallTarget(_fbb, ptr, _rehasher).Union();
    }
    case Target::IoctlTarget: {
      auto ptr = reinterpret_cast<const fbs::IoctlTargetT *>(value);
      return CreateIoctlTarget(_fbb, ptr, _rehasher).Union();
    }
    default: return 0;
  }
}

inline TargetUnion::TargetUnion(const TargetUnion &u) : type(u.type), value(nullptr) {
  switch (type) {
    case Target::CallTarget: {
      value = new fbs::CallTargetT(*reinterpret_cast<fbs::CallTargetT *>(u.value));
      break;
    }
    case Target::IoctlTarget: {
      value = new fbs::IoctlTargetT(*reinterpret_cast<fbs::IoctlTargetT *>(u.value));
      break;
    }
    default:
      break;
  }
}

inline void TargetUnion::Reset() {
  switch (type) {
    case Target::CallTarget: {
      auto ptr = reinterpret_cast<fbs::CallTargetT *>(value);
      delete ptr;
      break;
    }
    case Target::IoctlTarget: {
      auto ptr = reinterpret_cast<fbs::IoctlTargetT *>(value);
      delete ptr;
      break;
    }
    default: break;
  }
  value = nullptr;
  type = Target::NONE;
}

inline const fbs::Event *GetEvent(const void *buf) {
  return ::flatbuffers::GetRoot<fbs::Event>(buf);
}

inline const fbs::Event *GetSizePrefixedEvent(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fbs::Event>(buf);
}

inline bool VerifyEventBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fbs::Event>(nullptr);
}

inline bool VerifySizePrefixedEventBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fbs::Event>(nullptr);
}

inline void FinishEventBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fbs::Event> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedEventBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fbs::Event> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<fbs::EventT> UnPackEvent(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<fbs::EventT>(GetEvent(buf)->UnPack(res));
}

inline std::unique_ptr<fbs::EventT> UnPackSizePrefixedEvent(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<fbs::EventT>(GetSizePrefixedEvent(buf)->UnPack(res));
}

}  // namespace fbs

#endif  // FLATBUFFERS_GENERATED_EVENT_FBS_H_
